name: React-deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: docker login
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
      - name: Build Docker image
        run: docker build -t "${{ secrets.DOCKER_USERNAME }}/docker-react" -f Dockerfile.dev .
      - name: Run tests
        run: docker run -e CI=true "${{ secrets.DOCKER_USERNAME }}/docker-react" npm run test
      - name: Create deployment package
        run: zip -r deploy.zip . -x "*.git*" -x "*node_modules*" -x "*.github*"
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: MyApplicationName
          environment_name: MyApplication-Environment
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip